### ISSUE TITLE
E-web Blaster incorrect image

### ISSUE THREAD

**Issue by Gergall** [swccgpc/holotable#142]
E-Web Blaster image in SLA is the incorrect image, it is missing the deploy/forfeit boxes.

A correct image is attached.

![EwebBlaster](https://user-images.githubusercontent.com/6243118/110053264-0d950a80-7d27-11eb-8835-2a5a3ee6c8b7.gif)

**Comment by DevoKun** [comment]
Hello, @Gergall.

Thank you for seeing this card art issue and contributing the updated image.

The image quality is absolutely stunning! Do you mind me asking where you sourced this from or if you put this together? I ask because I would love to add more high-resolution images to the image archive and ultimately upgrade the crusty old gifs with versions that are, frankly, readable.

Because it was so high quality, I have added your updated card art to: https://github.com/swccgpc/holotable/blob/master/Images-HT/starwars/Hoth-Dark/hires/ewebblaster.png

Which automatically updated https://github.com/swccgpc/holotable/blob/master/Images-HT/starwars/Hoth-Dark/large/ewebblaster.gif

Which is now updated in our CDN: https://res.starwarsccg.org/cards/Hoth-Dark/large/ewebblaster.gif

Thank you for this work!

**Comment by Gergall** [comment]
Image was created by one of the PC graphics experts, Tamás Papp (Yoda007).  Who would I talk to about getting this updated into Scomp Link Access?

**Comment by EchoBaseTrooper** [comment]
It is updated in SLA. You might be seeing a cached image.

**Comment by Gergall** [comment]
I just checked from a different computer that has never used Scomp before.  It is the old image.  It is displaying  https://res.starwarsccg.org/cards/Images-HT/starwars/Hoth-Dark/large/ewebblaster.gif - that's different from your links above.

**Comment by EchoBaseTrooper** [comment]
Weird. I see the new image when I use SLA.
![image](https://user-images.githubusercontent.com/45436940/110181054-30c3c680-7dc8-11eb-83f2-c31324b15bc4.png)

**Comment by Gergall** [comment]
I just checked my wife's old macbookt has definitely never been to scomp before.  Old e-web image with no deploy/forfeit boxes.

Maybe I am doing something different from you?  Can we agree that https://res.starwarsccg.org/cards/Images-HT/starwars/Hoth-Dark/large/ewebblaster.gif is the old image still, you do see the old image there right?  What is this Images-HT folder of old images and why does scomp use it in some cases?

**Comment by EchoBaseTrooper** [comment]
Yes that link is still the old version for me. I think it is a recent update to have Scomp Link Access stop using the Images-HT images. I'm not sure why it's not using the newer location for everyone.

**Comment by DevoKun** [comment]
Hello, Gergall.


https://res.starwarsccg.org/cards/Images-HT/starwars/Hoth-Dark/large/ewebblaster.gif is not the correct URL.

The correct URL is: https://res.starwarsccg.org/cards/Hoth-Dark/large/ewebblaster.gif

Scomp was using an incorrect url path. That issue has been fixed now.

Thanks,

**Comment by Gergall** [comment]
Confirmed fixed! Huge thank you for figuring it out and repairing so quickly!
